### ISSUE TITLE
Support multiple branches

### ISSUE THREAD

**Issue by glenwinters** [x4121/git-amnesia#1]
When this runs `git log`, it just does it for the current branch. It would be helpful to see commits across all branches.

Scenario:
I make 5 commits on a feature branch and then switch back to master to pull in updates. If I run `git amnesia` at this time, I don't see the 5 commits because they're not in the history of the master branch.

**Comment by x4121** [comment]
Sorry for the long wait, this must have slipped under my radar.
Would `git log --all` solve this problem for you?

**Comment by glenwinters** [comment]
@x4121 I just played around with it, and that seems to work fine.

**Comment by x4121** [comment]
Thanks @glenwinters for bringing up this issue. The new version (0.0.3) should now be on rubygems.org
